Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -66,12 +66,18 @@ jobs:
           sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
           echo 'export PATH=/usr/local/cuda/bin:$PATH' >> ~/.bashrc
           source ~/.bashrc
+          NVCC_PATH=$(which nvcc)
+          echo "The path to nvcc is: $NVCC_PATH"
+          if [ -z "$NVCC_PATH" ]; then
+            echo "nvcc not found. Please check your CUDA installation."
+            exit 1
+          fi
           cd 3rdparty/kokkos
           mkdir build
           cd build
           cmake .. \
               -DCMAKE_CXX_COMPILER=${PWD}/../bin/nvcc_wrapper \
-              -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
+              -DCMAKE_CUDA_COMPILER=/usr/bin/nvcc \
               -DCMAKE_CUDA_HOST_COMPILER=/usr/bin/g++-10 \
               -DKokkos_ENABLE_CUDA=ON \
               -DKokkos_ARCH_AMPERE80=ON \
